CREATE AVAILABILITY GROUP [ag1]
WITH (DB_FAILOVER = ON, CLUSTER_TYPE = EXTERNAL)
FOR REPLICA ON
N'db1'
WITH (
ENDPOINT_URL = N'tcp://db1:5022',
AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
FAILOVER_MODE = EXTERNAL,
SEEDING_MODE = AUTOMATIC),
N'db2'
WITH (
ENDPOINT_URL = N'tcp://db2:5022',
AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
FAILOVER_MODE = EXTERNAL,
SEEDING_MODE = AUTOMATIC),
N'db3'
WITH (
ENDPOINT_URL = N'tcp://db3:5022',
AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
FAILOVER_MODE = EXTERNAL,
SEEDING_MODE = AUTOMATIC),
GO

ALTER AVAILABILITY_GROUP [ag1] GRANT CREATE ANY DATABASE; -- grant create any database permission
